### ISSUE TITLE
[META] Create Content Inventory of current site

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#3]
### Information we're trying to collect:
- How the pages/section fit into the site-tree/navigation
- Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

#### For @maryeb 
- [x] Gallery https://github.com/wesruv/jungcentralohio.org/issues/4
- [x] Intro https://github.com/wesruv/jungcentralohio.org/issues/5
- [x] Additional Resources https://github.com/wesruv/jungcentralohio.org/issues/6
- [x] Historic Building https://github.com/wesruv/jungcentralohio.org/issues/7

#### For Elaine
- [x] Bookstore https://github.com/wesruv/jungcentralohio.org/issues/8
- [x] OVAJA https://github.com/wesruv/jungcentralohio.org/issues/9
- [x] Upcoming Programs https://github.com/wesruv/jungcentralohio.org/issues/10
- [x] Welcome https://github.com/wesruv/jungcentralohio.org/issues/11

#### For @pascalmp 
- [x] Other Regional Events https://github.com/wesruv/jungcentralohio.org/issues/12
- [x] Saturday Discussions https://github.com/wesruv/jungcentralohio.org/issues/13
- [x] 4th Saturday Member's Gathering https://github.com/wesruv/jungcentralohio.org/issues/14
- [x] Homepage https://github.com/wesruv/jungcentralohio.org/issues/15

#### For @CraigKaminski 
- [x] Recent Programs https://github.com/wesruv/jungcentralohio.org/issues/16
- [x] Bollinger Lectures https://github.com/wesruv/jungcentralohio.org/issues/17
- [x] Local Jungian Analysis #18
